config/routes.rb
Rails.application.routes.draw do
  
  # get 'managers/index'

  # get 'managers/show'
  
  
  devise_for :managers
  as :manager do
    get 'managers/edit', to: 'devise/registrations#edit', :as => 'edit_manager_registration'
    put 'managers', to: 'devise/registrations#update', :as => 'manager_registration'
  end
  
  devise_scope :managers do
    post  "sessions/manager", to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :contacts do
    collection do
      post :confirm
    end  
  end  
  
  root to: 'events#index'
  resources :events do
    collection do 
      post :confirm
    end
  end
    
    resources :feeds
    resources :user_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :managers do 
       collection do 
         post :allow
         post :back
       end
    end  
    
    resource :about
    
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/inbox"
    end
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :events  
  def self.search(search)
    if search
      Event.where(['place LIKE ?', "%#{search}%"])
    else
      Event.all
    end
  end
  
  paginates_per 5
  
  default_scope -> { order(created_at: :desc) }
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :authenticate_manager!, only: [:index,:show,:allow,:back]
  before_action :guard_signup!, only: [:cancel, :new, :destroy, :create, :edit, :update]
  
  def index
    @events = Event.all
    @events = Event.search(params[:search])
    @events = Event.page(params[:page]).per(5)
    @contacts = Contact.all
    @contacts = Contact.page(params[:page]).per(5)
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def allow
    @event = Event.find(params[:id])
    @event.allow = true
    @event.save
    flash[:success] = "イベントを承認しました！"
    redirect_to managers_path
  end  
  
  def back
    @event = Event.find(params[:id])
    @event.allow = false
    @event.save
    flash[:success] = "イベントを元に戻しました！"
    redirect_to managers_path
  end  
  
  def destroy
      @event = Event.find(params[:id])
      @event.destroy
        flash[:success] ="イベントを削除しました！"
      redirect_to managers_path
  end 
  
  
  private  
   def event_params
    params.require(:event).permit(:title, :place, :event_date, :content, :user_id, :image, :image_cache, :allow)
   end 
   
   def search
   #ViewのFormで取得したパラメータをモデルに渡す
     @events = Event.search(params[:search])
    #  redirect_to managers_index_path
   end 
  
   def guard_signup!
    raise ActionController::RoutingError, 'NOT FOUND'
   end
  
   
  # def authenticate_manager!
  #   redirect_to events_path
  # end   
end

  

app/helpers/managers_helper.rb
module ManagersHelper
    
  def current_manager
    @current_manager ||= Manager.find_by(id: session[:id]) 
  end    
    
  def manager_signed_in?
    current_user.present?
  end  
end

app/views/managers/index.html.erb
<h1>管理者画面</h1>
  
    <li><%= link_to 'ログアウト', destroy_manager_session_path, method: :delete %></li>

      <header>
          <%= form_tag(events_path,:method => 'get') do %>
          <%= text_field_tag :search, '', placeholder: "例：東京、初心者、リラックス", :size =>'30' %>
          <%= submit_tag '検索する', class: 'btn btn-primary', :name => nil %>
          <% end %>
      </header>
    
  <% @events.each do |event| %>
    <div class= "container-fluid visible-xs visible-md visible-sm">
      <div class="center row">
        <div class= "col-md-6 col-sm-6 col-xs-12">
          <%= image_tag event.image , :size =>'240x240' %>
        </div>
        
        <div class="center event_list col-md-6 col-sm-6 col-xs-12">
          <h2><%=event.title %></h2>
          <h4><%= event.place %></h4>
          <%= event.event_date %>
          <br><%=link_to '記事を読む', event_path(event.id) %>
          
            <button type="button" class="btn btn-danger" btn-sm><%= link_to '削除する', managers_path(event.id),method: :delete ,data:{ confirm: '本当に削除してよろしいですか？'}  %></button>
         
          <% if event.allow == true  %>  
            <button type="button" class="btn btn-default" btn-lg><%= link_to "戻す", back_managers_path(id: event.id), method: :post%></button>
          <% else %>
            <button type="button" class="btn btn-success" btn-lg><%= link_to "承認", allow_managers_path(id: event.id), method: :post%></button>
          <% end %>
        </div> 
      </div>  
    </div>    
      <div class= "box visible-xl visible-lg">
        <div class="row">
          <div class= "event_image col-md-6 col-xs-12">
            <%=image_tag event.image , :size =>'240x240' %>
          </div>  
        
          <div class="center event_list col-md-6 col-xs-12">
            <h2><%=link_to event.title, event_path(event.id)  %></h2>
            <h4><%= event.place %></h4>
            <%= event.event_date %>
            <br><%=link_to '記事を読む', event_path(event.id) %>
          </div>  
        </div> 
        
          <button type="button" class="btn btn-danger" btn-sm><%= link_to '削除する', event_path(event.id),method: :delete ,data:{ confirm: '本当に削除してよろしいですか？'}  %></button>
        
        <% if event.allow == true  %>  
          <button type="button" class="btn btn-default" btn-lg><%= link_to "戻す", back_managers_path(id: event.id), method: :post%></button>
        <% else %>
          <button type="button" class="btn btn-success" btn-lg><%= link_to "承認", allow_managers_path(id: event.id), method: :post%></button>
        <% end %> 
      </div>
    </div>  
  <% end %> 
      
  <div class="center">
    <%= page_entries_info @events, entry_name: "Records" %>
    <%= paginate @events %>
  </div>

  
<h1>お問い合わせ一覧</h1>
  <%= @contacts.each do |contact| %>
      <div class="container-fluid center-block">     
        <div class="center row">
          <div class="center event_list">  
            <h2><%= contact.name %></h2>
            <h4><%= contact.email %></h4>
            <h4><%= contact.content %></h4>
              <%= link_to 'Show', contact %>
              <!--<%= link_to 'Edit', edit_contact_path(contact) %>-->
          </div>  
        </div>
      </div>

      <div class="container-fluid center-block"> 
        <div class="center row">
          <div class="center event_list">  
            <h2><%= contact.name %></h2>
            <h4><%= contact.email %></h4>
            <h4><%= contact.content %></h4>
              <%= link_to '詳細を見る', contact %>
              <!--<%= link_to 'Edit', edit_contact_path(contact) %>-->
          </div>  
        </div>
      </div>
    <% end %>  
    
    <div class="center">
      <%= page_entries_info @contacts, entry_name: "Records" %>
      <%= paginate @contacts %>
    </div>

app/views/managers/show.html.erb
<h1>Managers#show</h1>
<p>Find me in app/views/managers/show.html.erb</p>