config/routes.rb
Rails.application.routes.draw do
  
  # get 'managers/index'

  # get 'managers/show'
  
  
  devise_for :managers
  as :manager do
    get 'managers/edit', to: 'devise/registrations#edit', :as => 'edit_manager_registration'
    put 'managers', to: 'devise/registrations#update', :as => 'manager_registration'
  end
  
  devise_scope :managers do
    post  "sessions/manager", to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :contacts do
    collection do
      post :confirm
    end  
  end  
  
  root to: 'events#index'
  resources :events do
    collection do 
      post :confirm
    end
  end
    
    resources :feeds
    resources :user_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :managers do 
       collection do 
         post :allow
         post :back
       end
    end  
    
    resource :about
    
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/inbox"
    end
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  def add_error_event
    if title.blank?
      errors[:base] << "タイトルを入力して下さい"
    end
    if event_date.blank?
      errors[:base] << "開催日を入力して下さい"
    end
    if place.blank?
      errors[:base] << "開催場所を入力して下さい"
    end
    if content.blank?
      errors[:base] << "内容を入力して下さい"
    end
  end
  
  validates:title, :content, :place, :event_date, presence: true
  belongs_to :user
  belongs_to :manager, optional: true
  
  def self.search(search)
    if search
      Event.where(['place LIKE ?', "%#{search}%"])
    else
      Event.all
    end
  end
  
  paginates_per 5
  
  validate :add_error_event
  
  default_scope -> { order(created_at: :desc) }
  
end
  
  
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only:[:edit,:update,:destroy,:show]
  before_action :logged_in?, only:[:show]
  
  def index
   @events = Event.all
   @events = Event.search(params[:search])
   @events = Event.page(params[:page]).per(5)
  end
  
  def new
   if params[:back]
    @event = Event.new(event_params)
   else
    @event = Event.new
   end 
  end  
  
  def create
   @event = Event.new(event_params)
   @event.user_id = current_user.id
   if @event.save
    SampleMailer.send_event_create(current_user).deliver
    flash[:success] = "イベントが作成されました"
    redirect_to events_path
   else
    render'new'
   end 
  end
  
  def show
   @event = Event.find(params[:id])
  end 
  
  def edit
   @event = Event.find(params[:id])
   @event.image.cache! unless @event.image.blank?
  end
  
  def update
   @event = Event.find(params[:id])
   if @event.update(event_params)
     flash[:success] = "イベントを編集しました！"
     redirect_to events_path
   else
    render 'edit'
   end 
  end
  
  def destroy
    if current_user
      @event = Event.find(params[:id])
      @event.destroy
        flash[:success] ="イベントを削除しました！"
      redirect_to events_path
    end
  end 
  
  def confirm
   @event = Event.new(event_params)
   @event.user_id = current_user.id
   render :new if @event.invalid?
  end 
  
  private  
   def event_params
    params.require(:event).permit(:title, :place, :event_date, :content, :user_id, :image, :image_cache,{image: []}, :allow)
   end 
   
   def set_event
     @event = Event.find(params[:id])
   end 
   
   def search
   #ViewのFormで取得したパラメータをモデルに渡す
    @events = Event.search(params[:search])
   end
end  

app/helpers/events_helper.rb
module EventsHelper
    def choose_new_or_edit
      if action_name == 'new'||action_name == 'confirm'
        confirm_events_path
      elsif action_name == 'edit'
        event_path
      end
    end
end

app/views/events/_form.html.erb
<div class="input-group small-devices form-inline center-block">
          <ul class="center">
        <% @event.errors.full_messages.each do |msg| %>
          <li><font color="#FF0000"></font></li>
        <% end %>
          </ul>
    
    <div class="event-box">
      <%= bootstrap_form_for(@event, local: true, url: choose_new_or_edit) do |f|%>
        <div class="imagePreview"></div>
          <div class="input-group center-block event_form">
            <%= image_tag(@event.image) if @event.image %>
              <%= f.file_field :image, id: :image %>
          </div>
        
        <div class="event_form">
          <%= f.date_field :event_date,value: Time.now.strftime("%Y-%m-%d")%>
          <%= f.text_field :place, label: false, error: false, placeholder: "開催場所" %>
        </div>
        
        <div class="event_form">
          <%= f.text_field :title, size:"80", label: false, error: false, placeholder: "タイトルを入力" %>
          
          <%= f.text_area :content, size:"80x10",label: false, error: false %>
        </div>
        
        <div class="button">
        <input type="submit" type="button" class="far fa-envelope btn-success center-block"value="投稿する &#xf0e0">
        </div>
  
      <% end %>
    </div>  
</div>

app/views/events/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

  <div class="center event-box">
    <%= bootstrap_form_for(@event,url: events_path,local:true)do |f|%>
      <%= f.hidden_field:title %>
      <%= f.hidden_field:content %>
      <%= f.hidden_field:place %>
      <%= f.hidden_field:event_date %>
      <%= f.hidden_field:image_cache, :size =>'320x320' %>
         
      <%= image_tag @event.image , :size =>'320x320' %>
      <h4><%= @event.title %></h4>
      <h5><%= @event.event_date %></h5>
      <h5><%= @event.place %></h5>
      <h5><%= @event.content %></h5>
    
      <div class="button">
        <input type="submit" type="button" class="far fa-envelope btn-success center-block"value="投稿する &#xf0e0" data-disable-with="投稿中...">
      </div>
    <% end %>
    
    <%= bootstrap_form_for(@event, url: new_event_path, local: true,method: 'get')do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field:place %>
      <%= f.hidden_field:event_date %>
      <%= f.hidden_field :image_cache %>
      
      <%= f.submit "戻る",class: 'btn btn-warning button', name: 'back' %>
    
    <% end %>  
  </div>    
    
    

app/views/events/edit.html.erb
<h2>イベントを編集する</h2>
 <div class="center">
 <%= render 'form' %>
 </div>
 

app/views/events/index.html.erb
<%= notice %>
  <header>
    <div class="image_area visible-lg">
    </div> 
    <div class="image_phone visible-xs">
    </div> 
    <div class="image_pad visible-md visible-sm">
    </div>
    
    <form class="center-block input-group small-devices form-inline search-box">
      <%= form_tag(events_path,:method => 'get') do %>
        <%= text_field_tag :search, params[:search], placeholder: "場所、開催日", :size =>'20' %>
        <button type="submit" class="button1 fas fa-search"></button>
      <% end %>
    </form>  
  </header>
  <% @events.each do |event| %>
    <% if event.allow == false  %>
      <div class= "container-fluid visible-xs visible-md visible-sm">
          <div class="center row">
            <div class= "col-md-4 col-sm-4 visible-xl visible-lg">
              <%= image_tag event.image, :size =>'240x240' %>
            </div> 
            <div class= "col-md-4 col-sm-4 visible-md visible-sm">
              <%=image_tag event.image , :size =>'180x180' %>
            </div>  
            <div class= "visible-xs">
              <%=image_tag event.image , :size =>'140x140' %>
            </div> 
            <div class="center event_list col-md-4 col-sm-4">
              <h2><%=link_to event.title, event_path(event.id)  %></h2>
              <h4><%= event.place %></h4>
              <%= event.event_date %>
              <br><div class="event-box"><%=link_to '記事を読む', event_path(event.id) %></div>
            </div>  
          </div>
          
          <% if logged_in?  %>
            <% if event.user == current_user %>
              <button type="button" class="btn btn-warning" btn-sm><%= link_to "編集する", edit_event_path(event.id) %></button>
              <button type="button" class="far fa-trash-alt btn btn-danger" btn-sm><%= link_to '削除する', event_path(event.id),method: :delete ,data:{ confirm: '本当に削除してよろしいですか？'}  %></button>
            <% end %>
          <% else %>
            <% link_to new_user_session_path %>
          <% end %>
      </div>  
      
        <div class= "box visible-xl visible-lg">
          <div class="row">
            <div class= "event_image col-md-6 col-xs-12">
              <%=image_tag event.image , :size =>'240x240' %>
            </div>  
          
            <div class="center event_list col-md-6 col-xs-12">
              <h2><%=link_to event.title, event_path(event.id)  %></h2>
              <h4><%= event.place %></h4>
              <%= event.event_date %>
              <br><div class="event-box"><%=link_to '記事を読む', event_path(event.id) %></div>  
            </div>  
          </div>
          
          <% if logged_in?  %>
            <% if event.user.id == current_user.id %>
              <button type="button" class="btn btn-warning" btn-sm><%= link_to "編集する", edit_event_path(event.id) %></button>
              <button type="button" class="btn btn-danger" btn-sm><%= link_to '削除する', event_path(event.id),method: :delete ,data:{ confirm: '本当に削除してよろしいですか？'}  %></button>
            <% end %>
          <% else %>
            <% link_to new_user_session_path %>
          <% end %>
        </div>
    <% end %>
  <% end %> 
  <div class="center">
  <%= page_entries_info @events %>
  <%= paginate @events %>
  </div>

app/views/events/new.html.erb
 <h2>【イベントを作成する】</h2>
 <%= render 'form' %>

app/views/events/show.html.erb
<h1>イベントの詳細</h1>
  <div class= "event_show event_list">
    <div class="center row">
      <div class= "col-md-4 col-sm-4 visible-xl visible-lg">
        <%= image_tag @event.image, :size =>'240x240' %>
      </div> 
      <div class= "col-md-4 col-sm-4 visible-md visible-sm visible-xs">
        <%= image_tag @event.image, :size =>'140x140' %>
      </div>
      <div class="center col-md-4 col-sm-4">
        <%= @event.user.name %>
        <p>タイトル: <%= @event.title %></p>
        <p>開催日: <%= @event.event_date %></p>
        <p>場所: <%= @event.place %></p>
        <%= @event.content%>
      </div> 
    </div>   
  </div>
  <div class="center">
  <%= link_to '一覧に戻る', events_path %>
  </div>