config/routes.rb
Rails.application.routes.draw do
  
  # get 'managers/index'

  # get 'managers/show'
  
  
  devise_for :managers
  as :manager do
    get 'managers/edit', to: 'devise/registrations#edit', :as => 'edit_manager_registration'
    put 'managers', to: 'devise/registrations#update', :as => 'manager_registration'
  end
  
  devise_scope :managers do
    post  "sessions/manager", to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :contacts do
    collection do
      post :confirm
    end  
  end  
  
  root to: 'events#index'
  resources :events do
    collection do 
      post :confirm
    end
  end
    
    resources :feeds
    resources :user_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :managers do 
       collection do 
         post :allow
         post :back
       end
    end  
    
    resource :about
    
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/inbox"
    end
end

app/views/layouts/about.html.erb
<h1>FreeYogaについて</h1>

<p>都心の高いヨガスタジオではなく、もっと気軽に近所の公園などで知人友人を集めてヨガをやりたい！
そんな軽い気持ちからこのサイトを作り始めました。

無料のイベントのみ掲載が許可されています。

ヨガインストラクターの資格を取得したばかりで教える場所や機会を探している方や、ヨガに興味はあってもスタジオに通うのに一歩踏み出せない、そんな方に使ってもらえればと思います。

もちろん普段スタジオなどでヨガを教えている方も、新たに生徒さんを増やす目的で使って頂いてもかまいません。

ヨガをもっと自由に、毎日の暮らしと共に。</p>

app/views/layouts/application.html.erb
    <!DOCTYPE html>
<html>
  <head>
    <title>FREE_YOGA</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
        <!--ここから下がハンバーガーメニューの描画↓↓-->
        <button type="button" class="navbar-toggle collapsed"   
        data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>  
        <!--ここから上がハンバーガーメニューの描画-->
        <div class="navbar-logo"><%=link_to image_tag('logoyoga.jpg', :size =>'61x53'), '/' %>
        </div>
        <ul class="navbar-nav navbar-about">
          <li class="col-sm"><%= link_to '初めての方へ', about_path %></li>
        </ul>
        <div id="gnavi" class="collapse navbar-collapse"> <!--ここからがメニューリストの部分-->
          <ul class="nav navbar-nav">
          <div class="app-header-inner nav navbar-nav">
            <% if logged_in? %>
              <li class="col-xs"><%= link_to '新しく投稿する', new_event_path %></li>
              <li class="col-xs"><%= link_to "Profile", user_path(current_user.id) %></li>
              <li class="col-xs"><%= link_to "Logout", user_session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li class="col-xs"><%= link_to "ヨガインストラクターの登録", new_user_path %></li>
              <li class="col-xs"><%= link_to "Login", new_user_session_path %></li>
            <% end %>
            <li class="col-sm"><%= link_to "お問い合わせ", new_contact_path %></li>
          </div>
          </ul>
        </div>
      </nav>
      
    
      <div class="clearfix:after">  
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <% end %>
        <%= yield %>  
      </div>  
    
    
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright &copy; FreeYoga</p>
      </div> 
    </footer>
  </body>
</html>

    